import {useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../../components/ui/dialog';
import {useBoard,api,mutate} from '../services/sitesStore';
import {activePeople,matchPerson,normalizeName,type OcrRow,type Shift} from '../../domain';
import {DEPARTMENTS} from '../data/departments';
import {applyImageAdjustments,DEFAULT_ADJUSTMENTS} from '../utils/imagePreprocessing';
export function OcrReview({isOpen,onClose,shift}:{isOpen:boolean;onClose:()=>void;shift:Shift;[key:string]:any}){
 const state=useBoard();const [image,setImage]=useState('');const [preview,setPreview]=useState('');const [adjust,setAdjust]=useState(DEFAULT_ADJUSTMENTS);const [zoom,setZoom]=useState(100);const [text,setText]=useState('');const [rows,setRows]=useState<OcrRow[]>([]);const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [dateConfirmed,setDateConfirmed]=useState(false);const [replaceManual,setReplaceManual]=useState(false);const [budget,setBudget]=useState<any>();const [instructions,setInstructions]=useState('');const [retryRow,setRetryRow]=useState('');const [retryUsed,setRetryUsed]=useState(false);
 const people=activePeople(state.board.roster,state.date,shift).filter(p=>p.role==='operator');
 useEffect(()=>{if(isOpen)api('/api/budget').then(setBudget).catch(()=>{});},[isOpen,busy]);
 useEffect(()=>{let active=true;if(image)applyImageAdjustments(image,adjust).then(v=>{if(active)setPreview(v);}).catch(e=>setError(e.message));return()=>{active=false;};},[image,adjust]);
 const patch=(id:string,values:Partial<OcrRow>)=>setRows(rows.map(r=>r.rowId===id?{...r,...values,reviewed:values.reviewed??false}:r));
 const file=async(f?:File)=>{if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>15000000){setError('Použijte JPG, PNG nebo WebP do 15 MB.');return;}const reader=new FileReader();reader.onload=()=>{setImage(String(reader.result));setAdjust(DEFAULT_ADJUSTMENTS);setResult(null);setRows([]);setRetryUsed(false);setError('');};reader.readAsDataURL(f);};
 const process=async(retry=false)=>{if(!dateConfirmed){setError('Potvrďte datum a směnu rozpisu.');return;}setBusy(true);setError('');try{if(retry&&(!retryRow||!image))throw Error('Vyberte nejasný řádek a jeho výřez.');if(retry&&adjust.crop.width===100&&adjust.crop.height===100)throw Error('Pro druhý pokus vyberte menší výřez fotografie.');const picture=image?await applyImageAdjustments(image,adjust):undefined;const data=await api('/api/ocr',{date:state.date,shift,imageBase64:picture,textInput:picture?undefined:text,mimeType:'image/jpeg',customInstructions:instructions,retryOf:retry?result.importId:undefined});if(retry){setRetryUsed(true);const candidate=data.rows.filter((r:OcrRow)=>r.kind!=='excluded');if(candidate.length!==1)throw Error('Výřez neobsahuje jednoznačný řádek. Opravte ho ručně.');patch(retryRow,{...candidate[0],rawText:rows.find(r=>r.rowId===retryRow)?.rawText??'',rowId:retryRow,reviewed:false});}else{setResult(data);setRows(data.rows.map((r:OcrRow)=>{const matched=matchPerson(r.name,people);return {...r,personId:matched.length===1?matched[0].id:undefined,reviewed:false};}));setRetryUsed(false);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const latest=state.board.imports.filter(i=>i.shift===shift).at(-1);const included=rows.filter(r=>r.kind!=='excluded');const manual=state.board.operators.filter(o=>o.shift===shift&&o.source!=='ocr');const previousNames=new Set((latest?.rows??[]).filter((r:OcrRow)=>r.kind!=='excluded').map((r:OcrRow)=>normalizeName(r.name)));const currentNames=new Set(included.map(r=>normalizeName(r.name)));const added=included.filter(r=>!previousNames.has(normalizeName(r.name)));const missing=(latest?.rows??[]).filter((r:OcrRow)=>r.kind!=='excluded'&&!currentNames.has(normalizeName(r.name)));
 const commit=async()=>{setBusy(true);try{if(rows.some(r=>!r.reviewed))throw Error('Potvrďte kontrolu všech řádků včetně vyřazených.');await mutate('import',{importId:result.importId,shift,rows,replaceManual});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Dialog open={isOpen} onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="zf-panel !max-w-[95vw] !w-[1400px]"><DialogTitle>Načíst rozpis z fotografie</DialogTitle><DialogDescription>Datum {state.date} · směna {shift} · celá směna, transport i VNA</DialogDescription><label className="inline"><input type="checkbox" checked={dateConfirmed} onChange={e=>setDateConfirmed(e.target.checked)}/>Potvrzuji provozní datum a směnu, i pokud směna končí po půlnoci.</label>{budget&&<p className="muted">OCR tento měsíc: {budget.spent.toFixed(2)} Kč · rezervováno {budget.reserved.toFixed(2)} Kč · aplikační limit {budget.limit} Kč</p>}{error&&<p className="error" role="alert">{error}</p>}
 <div className="review-grid"><div><label>Fotografie<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>file(e.target.files?.[0])}/></label>{image?<><div className="actions"><button disabled={busy} onClick={()=>setAdjust({...adjust,rotation:(adjust.rotation+90)%360})}>Otočit 90°</button><button disabled={busy} onClick={()=>{setImage('');setPreview('');setResult(null);setRows([]);}}>Použít text</button><label>Přiblížení<input type="range" min="50" max="300" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div><details><summary>Ořez fotografie / výřezu (procenta)</summary><div className="fields">{(['x','y','width','height'] as const).map(k=><label key={k}>{{x:'Zleva',y:'Shora',width:'Šířka',height:'Výška'}[k]}<input type="number" min={k==='width'||k==='height'?1:0} max="100" value={adjust.crop[k]} onChange={e=>{const crop={...adjust.crop,[k]:Number(e.target.value)};crop.x=Math.min(99,Math.max(0,crop.x));crop.y=Math.min(99,Math.max(0,crop.y));crop.width=Math.max(1,Math.min(crop.width,100-crop.x));crop.height=Math.max(1,Math.min(crop.height,100-crop.y));setAdjust({...adjust,crop});}}/></label>)}</div></details><div className="photo">{preview&&<img src={preview} alt="Fotografie rozpisu pro porovnání s OCR" style={{width:zoom+'%'}}/>}</div></>:<label>Rozpis jako text (jméno; oddělení)<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Jméno Příjmení; hovc"/></label>}<details><summary>Pokyny pro čtení</summary><textarea maxLength={4000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></details><div className="actions"><button className="primary" disabled={busy||!dateConfirmed||(!image&&!text.trim())||!!result} onClick={()=>process()}>{busy?'Zpracování…':'Rozpoznat a zobrazit náhled'}</button>{result&&<button disabled={busy} onClick={()=>{setResult(null);setRows([]);}}>Nový náhled</button>}</div>{result&&image&&!retryUsed&&<div className="fields"><label>Nejasný řádek pro jeden další pokus<select value={retryRow} onChange={e=>setRetryRow(e.target.value)}><option value="">Vyberte řádek</option>{rows.map(r=><option key={r.rowId} value={r.rowId}>{r.name||r.rawText||'Nečitelné'}</option>)}</select></label><button disabled={busy||!retryRow} onClick={()=>process(true)}>Přečíst vybraný výřez</button></div>}</div>
 <div>{!result&&<p className="muted">Po rozpoznání zde zkontrolujete přesná jména, oddělení a absence. Nic se zatím nezmění na nástěnce.</p>}{result&&<><p>Revize {(latest?.revision??0)+1} · {added.length} nových jmen · {missing.length} jmen proti předchozí fotce chybí</p>{missing.length>0&&<p className="muted">Chybí: {missing.map((r:OcrRow)=>r.name).join(', ')}</p>}{rows.map(r=><div key={r.rowId} className={'ocr-row '+(!r.reviewed?'needs':'')}><p className="muted">Původně: {r.rawText||'Nečitelné'} {r.issues.length>0&&'· '+r.issues.join(' ')}</p><div className="fields"><label>Jméno<input maxLength={100} value={r.name} onChange={e=>patch(r.rowId,{name:e.target.value,personId:undefined})}/></label><label>Význam<select value={r.kind} onChange={e=>patch(r.rowId,{kind:e.target.value as any})}><option value="operator">Operátor</option><option value="absence">Absence</option><option value="excluded">Vyřadit řádek</option><option value="unclear">Nejasné</option></select></label>{r.kind==='operator'&&<><label>Oddělení<select value={r.departmentId} onChange={e=>patch(r.rowId,{departmentId:e.target.value})}><option value="unassigned">Doplnit oddělení</option>{DEPARTMENTS.filter(d=>d.id!=='unassigned').concat(state.board.custom_departments).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Technika<select value={r.machineType} onChange={e=>patch(r.rowId,{machineType:e.target.value as any})}><option>NONE</option><option>LL</option><option>RTR</option></select></label></>}{r.kind==='absence'&&<label>Důvod<select value={r.absenceReason??''} onChange={e=>patch(r.rowId,{absenceReason:e.target.value as any})}><option value="">Vyberte důvod</option><option>Absence</option><option>Dovolená</option><option>PN</option></select></label>}<label>Osoba ze stálého seznamu<select value={r.personId??''} onChange={e=>patch(r.rowId,{personId:e.target.value||undefined})}><option value="">Nepřiřazená / externí osoba</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} {p.distinction} ({p.team})</option>)}</select></label></div><label className="inline"><input type="checkbox" checked={!!r.reviewed} onChange={e=>patch(r.rowId,{reviewed:e.target.checked})}/>Řádek jsem ověřil podle fotografie</label></div>)}{manual.length>0&&<><p>Ruční údaje budou zachovány: {manual.map(o=>o.name+' ('+o.departmentId+')').join(', ')}.</p><label className="inline"><input type="checkbox" checked={replaceManual} onChange={e=>setReplaceManual(e.target.checked)}/>Výslovně nahradit i uvedené ruční údaje tímto rozpisem</label></>}<p className="muted">Vyřazený řádek nenahrazuje absenci. Nenalezení stálí operátoři zůstanou k ověření.</p><button className="primary" disabled={busy||!dateConfirmed||rows.some(r=>!r.reviewed)} onClick={commit}>Potvrdit a uložit rozpis</button></>}</div></div></DialogContent></Dialog>;
}
