import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../../components/ui/dialog';
import {useBoard,mutate} from '../services/sitesStore';
import {audit,activePeople,type Person,type Shift} from '../../domain';
import {DEPARTMENTS} from '../data/departments';

export function RosterPanel({shift}:{shift:Shift}){
 const state=useBoard();const [open,setOpen]=useState(false);const [tab,setTab]=useState<'check'|'people'>('check');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [draft,setDraft]=useState<Person[]>([]);const [names,setNames]=useState('');const [team,setTeam]=useState<'transport'|'vna'>('transport');const [role,setRole]=useState<'operator'|'lead'>('operator');const [resolution,setResolution]=useState<Record<string,string>>({});const check=audit(state.board,state.date,shift);
 const show=(value:'check'|'people')=>{setDraft(structuredClone(state.board.roster));setTab(value);setOpen(true);setError('');};
 const run=async(fn:()=>Promise<any>)=>{setBusy(true);try{await fn();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const add=()=>{const list=names.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);setDraft([...draft,...list.map(name=>({id:crypto.randomUUID(),name,shift,team,role,aliases:[],distinction:'',activeFrom:state.date,activeTo:null}))]);setNames('');};
 const patch=(id:string,values:Partial<Person>)=>setDraft(draft.map(p=>p.id===id?{...p,...values}:p));
 const assign=(p:Person,selection:string)=>run(async()=>{
  if(selection==='other'){const note=resolution[p.id]?.trim();if(!note)throw Error('Napište důvod.');await mutate('resolve',{personId:p.id,shift,note});return;}
  if(!selection)return;
  const absence=['Absence','Dovolená','PN'].includes(selection);const old=state.board.operators.find(o=>o.personId===p.id&&o.shift===shift);
  await mutate('operators',[{...old,id:old?.id??'person-'+p.id,personId:p.id,name:p.name,shift,machineType:old?.machineType??'NONE',departmentId:absence?'unassigned':selection,status:absence?'absence':'active',absenceReason:absence?selection:undefined,lastMovedAt:new Date().toISOString()}]);
 });
 return <><div className="roster-bar"><button onClick={()=>show('check')} className={check.pending?'pending':''}>OP {check.total} · evidováno {check.resolved} · {check.hasImport?'ověřit '+check.pending:'čeká na rozpis'}</button><span>Transport {check.rows.filter(r=>r.person.team==='transport').length} · VNA {check.rows.filter(r=>r.person.team==='vna').length}</span><button onClick={()=>show('people')}>Lidé směny {shift}</button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="zf-panel !max-w-5xl"><DialogTitle>{tab==='people'?'Lidé směny '+shift:'Kontrola směny '+shift}</DialogTitle><DialogDescription>{state.date} · vedoucí nejsou zahrnuti v počtu OP</DialogDescription><div className="actions"><button onClick={()=>setTab('check')}>Denní kontrola</button><button onClick={()=>setTab('people')}>Stálý seznam</button></div>{error&&<p className="error" role="alert">{error}</p>}
 {tab==='check'?<><p className="muted">{check.hasImport?'Kontrola vychází z posledního potvrzeného rozpisu.':'Pro tento den a směnu zatím není potvrzený rozpis. Absence se nedoplňují automaticky.'}</p>{!check.total&&<p>Nejprve přidejte stálé operátory do seznamu směny.</p>}{check.rows.map(r=><div className="person" key={r.person.id}><b>{r.person.name}</b> {r.person.distinction} <span className="muted">· {r.person.team==='vna'?'VNA':'Transport'} · {{waiting:'Čeká na rozpis',missing:'K ověření – chybí zařazení nebo důvod',conflict:'K ověření – více záznamů',done:'Vyřešeno',manual:'Vyřešeno ručně'}[r.status]} · {r.found?'nalezen v OCR':'nenalezen v OCR'}</span>{r.note&&<p>{r.note}</p>}<div className="fields"><label>Doplnit zařazení<select disabled={busy} value="" onChange={e=>assign(r.person,e.target.value)}><option value="">Vyberte oddělení či absenci</option>{DEPARTMENTS.filter(d=>d.id!=='unassigned').concat(state.board.custom_departments).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}{['Absence','Dovolená','PN'].map(a=><option key={a}>{a}</option>)}</select></label><label>Jiný důvod<input value={resolution[r.person.id]??''} onChange={e=>setResolution({...resolution,[r.person.id]:e.target.value})} maxLength={500}/></label><button disabled={busy} onClick={()=>assign(r.person,'other')}>Uložit důvod</button></div></div>)}</>:<>
 <div className="fields"><label>Část směny<select value={team} onChange={e=>setTeam(e.target.value as any)}><option value="transport">Transport</option><option value="vna">VNA</option></select></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as any)}><option value="operator">Operátor</option><option value="lead">Team Leader</option></select></label></div><label>Jména — každé na samostatný řádek<textarea value={names} onChange={e=>setNames(e.target.value)} placeholder="Vložte přesná jména"/></label><button onClick={add} disabled={!names.trim()}>Přidat do náhledu</button>
 {draft.filter(p=>p.shift===shift).map(p=><div className="person" key={p.id}><div className="fields"><label>Jméno<input value={p.name} onChange={e=>patch(p.id,{name:e.target.value})}/></label><label>Rozlišení jmen<input value={p.distinction} onChange={e=>patch(p.id,{distinction:e.target.value})} placeholder="Např. osobní číslo"/></label><label>Část<select value={p.team} onChange={e=>patch(p.id,{team:e.target.value as any})}><option value="transport">Transport</option><option value="vna">VNA</option></select></label><label>Role<select value={p.role} onChange={e=>patch(p.id,{role:e.target.value as any})}><option value="operator">OP</option><option value="lead">Team Leader</option></select></label><label>Potvrzené zkratky (oddělit čárkou)<input value={p.aliases.join(', ')} onChange={e=>patch(p.id,{aliases:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Platí od<input type="date" value={p.activeFrom} onChange={e=>patch(p.id,{activeFrom:e.target.value})}/></label><label>Platí do<input type="date" value={p.activeTo??''} onChange={e=>patch(p.id,{activeTo:e.target.value||null})}/></label></div></div>)}<p className="quiet-count">Náhled: {activePeople(draft,state.date,shift).filter(p=>p.role==='operator').length} OP · {activePeople(draft,state.date,shift).filter(p=>p.role==='lead').length} vedoucí</p><button className="primary" disabled={busy} onClick={()=>run(()=>mutate('roster',draft))}>{busy?'Ukládání…':'Potvrdit stálý seznam'}</button></>}
 </DialogContent></Dialog></>;
}
