import {Users,UserPlus,ClipboardCheck,Search,ChevronDown,ShieldCheck,Save} from 'lucide-react';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../../components/ui/dialog';
import {useBoard,mutate} from '../services/sitesStore';
import {audit,activePeople,normalizeName,type Person,type Shift} from '../../domain';
import {DEPARTMENTS} from '../data/departments';

export function RosterPanel({shift}:{shift:Shift}){
 const state=useBoard();const [query,setQuery]=useState('');const [filter,setFilter]=useState<'all'|'transport'|'vna'>('all');const [onlyPending,setOnlyPending]=useState(false);const [saved,setSaved]=useState(false);const [open,setOpen]=useState(false);const [tab,setTab]=useState<'check'|'people'>('check');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [draft,setDraft]=useState<Person[]>([]);const [names,setNames]=useState('');const [team,setTeam]=useState<'transport'|'vna'>('transport');const [role,setRole]=useState<'operator'|'lead'>('operator');const [resolution,setResolution]=useState<Record<string,string>>({});const check=audit(state.board,state.date,shift);
 const show=(value:'check'|'people')=>{setDraft(structuredClone(state.board.roster));setTab(value);setOpen(true);setError('');setQuery('');setSaved(false);};
 const run=async(fn:()=>Promise<any>)=>{setBusy(true);try{await fn();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const add=()=>{setSaved(false);const list=names.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);setDraft([...draft,...list.map(name=>({id:crypto.randomUUID(),name,shift,team,role,aliases:[],distinction:'',activeFrom:state.date,activeTo:null}))]);setNames('');};
 const patch=(id:string,values:Partial<Person>)=>{setSaved(false);setDraft(draft.map(p=>p.id===id?{...p,...values}:p));};
 const assign=(p:Person,selection:string)=>run(async()=>{
  if(selection==='other'){const note=resolution[p.id]?.trim();if(!note)throw Error('Napište důvod.');await mutate('resolve',{personId:p.id,shift,note});return;}
  if(!selection)return;
  const absence=['Absence','Dovolená','PN'].includes(selection);const old=state.board.operators.find(o=>o.personId===p.id&&o.shift===shift);
  await mutate('operators',[{...old,id:old?.id??'person-'+p.id,personId:p.id,name:p.name,shift,machineType:old?.machineType??'NONE',departmentId:absence?'unassigned':selection,status:absence?'absence':'active',absenceReason:absence?selection:undefined,lastMovedAt:new Date().toISOString()}]);
 });
 const visible=(p:Person)=>(filter==='all'||p.team===filter)&&normalizeName(p.name+' '+p.distinction).includes(normalizeName(query));
 const active=activePeople(draft,state.date,shift);const isActive=(p:Person)=>p.activeFrom<=state.date&&(!p.activeTo||p.activeTo>=state.date);
 const filtered=draft.filter(p=>p.shift===shift&&visible(p)).sort((a,b)=>Number(b.role==='lead')-Number(a.role==='lead')||a.name.localeCompare(b.name,'cs'));
 return <><div className="roster-bar staff-bar"><button onClick={()=>show('check')} className={check.pending?'pending':''}>OP {check.total} · evidováno {check.resolved} · {check.hasImport?'ověřit '+check.pending:'čeká na rozpis'}</button><span>Transport {check.rows.filter(r=>r.person.team==='transport').length} · VNA {check.rows.filter(r=>r.person.team==='vna').length}</span><button className="staff-open" onClick={()=>show('people')}><Users size={16}/>Lidé směny {shift}</button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="zf-panel staff-dialog !max-w-5xl"><div className="staff-heading"><span className="staff-heading-icon"><Users size={23}/></span><div><DialogTitle>{tab==='people'?'Lidé směny '+shift:'Kontrola směny '+shift}</DialogTitle><DialogDescription>{state.date} · vedoucí nejsou zahrnuti v počtu OP</DialogDescription></div></div><div className="staff-tabs"><button aria-pressed={tab==='check'} onClick={()=>setTab('check')}><ClipboardCheck size={17}/>Denní kontrola</button><button aria-pressed={tab==='people'} onClick={()=>setTab('people')}><Users size={17}/>Stálý seznam</button></div><div className="staff-tools"><label className="staff-search"><Search size={17}/><input aria-label="Hledat zaměstnance" placeholder="Hledat jméno nebo osobní číslo…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="staff-filters">{(['all','transport','vna'] as const).map(t=><button key={t} aria-pressed={filter===t} onClick={()=>setFilter(t)}>{{all:'Všichni',transport:'Transport',vna:'VNA'}[t]}</button>)}</div></div>{error&&<p className="error" role="alert">{error}</p>}
 {tab==='check'?<><p className="muted">{check.hasImport?'Kontrola vychází z posledního potvrzeného rozpisu.':'Pro tento den a směnu zatím není potvrzený rozpis. Absence se nedoplňují automaticky.'}</p>{!check.total&&<p>Nejprve přidejte stálé operátory do seznamu směny.</p>}<label className="inline staff-pending-toggle"><input type="checkbox" checked={onlyPending} onChange={e=>setOnlyPending(e.target.checked)}/>Jen k ověření</label>{check.rows.filter(r=>visible(r.person)&&(!onlyPending||['missing','conflict'].includes(r.status))).map(r=><div className={"person staff-check "+r.status} key={r.person.id}><b>{r.person.name}</b> {r.person.distinction} <span className="muted">· {r.person.team==='vna'?'VNA':'Transport'} · {{waiting:'Čeká na rozpis',missing:'K ověření – chybí zařazení nebo důvod',conflict:'K ověření – více záznamů',done:'Vyřešeno',manual:'Vyřešeno ručně'}[r.status]} · {r.found?'nalezen v OCR':'nenalezen v OCR'}</span>{r.note&&<p>{r.note}</p>}<div className="fields"><label>Doplnit zařazení<select disabled={busy} value="" onChange={e=>assign(r.person,e.target.value)}><option value="">Vyberte oddělení či absenci</option>{DEPARTMENTS.filter(d=>d.id!=='unassigned').concat(state.board.custom_departments).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}{['Absence','Dovolená','PN'].map(a=><option key={a}>{a}</option>)}</select></label><label>Jiný důvod<input value={resolution[r.person.id]??''} onChange={e=>setResolution({...resolution,[r.person.id]:e.target.value})} maxLength={500}/></label><button disabled={busy} onClick={()=>assign(r.person,'other')}>Uložit důvod</button></div></div>)}</>:<>
 <div className="staff-stats"><div><span>Operátoři</span><strong>{active.filter(p=>p.role==='operator').length}<small> OP</small></strong></div><div><span>Transport / VNA</span><strong>{active.filter(p=>p.role==='operator'&&p.team==='transport').length}<small> / </small>{active.filter(p=>p.role==='operator'&&p.team==='vna').length}</strong></div><div><span>Vedoucí</span><strong>{active.filter(p=>p.role==='lead').length}<small> / 2</small></strong></div></div><details className="staff-add"><summary><UserPlus size={18}/>Přidat zaměstnance<ChevronDown size={16}/></summary><div className="staff-add-body"><div className="fields"><label>Část směny<select value={team} onChange={e=>setTeam(e.target.value as any)}><option value="transport">Transport</option><option value="vna">VNA</option></select></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as any)}><option value="operator">Operátor</option><option value="lead">Team Leader</option></select></label></div><label>Jména — každé na samostatný řádek<textarea value={names} onChange={e=>setNames(e.target.value)} placeholder="Vložte přesná jména"/></label><button onClick={add} disabled={busy||!names.trim()}>Přidat do náhledu</button></div></details>
 {!filtered.length&&<div className="staff-empty"><Users size={32}/><h3>{query?'Žádná shoda':'Seznam je zatím prázdný'}</h3><p className="muted">{query?'Zkuste jiné jméno nebo filtr.':'Přidejte jména jednotlivě nebo vložte celý seznam.'}</p></div>}{filtered.map(p=><details className="person staff-person" key={p.id}><summary><span className={'staff-avatar '+p.team}>{p.role==='lead'?<ShieldCheck size={19}/>:p.name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><span className="staff-identity"><b>{p.name||'Doplňte jméno'}</b><small>{p.distinction||'Směna '+shift} · {p.team==='vna'?'VNA':'Transport'}</small></span><span className="staff-badge">{p.role==='lead'?'Vedoucí':'Operátor'}</span>{!isActive(p)&&<span className="staff-inactive">{p.activeFrom>state.date?'Od '+p.activeFrom:'Ukončeno'}</span>}<ChevronDown size={16}/></summary><div className="fields staff-edit"><label>Jméno<input value={p.name} onChange={e=>patch(p.id,{name:e.target.value})}/></label><label>Rozlišení jmen<input value={p.distinction} onChange={e=>patch(p.id,{distinction:e.target.value})} placeholder="Např. osobní číslo"/></label><label>Část<select value={p.team} onChange={e=>patch(p.id,{team:e.target.value as any})}><option value="transport">Transport</option><option value="vna">VNA</option></select></label><label>Role<select value={p.role} onChange={e=>patch(p.id,{role:e.target.value as any})}><option value="operator">OP</option><option value="lead">Team Leader</option></select></label><label>Potvrzené zkratky (oddělit čárkou)<input value={p.aliases.join(', ')} onChange={e=>patch(p.id,{aliases:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Platí od<input type="date" value={p.activeFrom} onChange={e=>patch(p.id,{activeFrom:e.target.value})}/></label><label>Platí do<input type="date" value={p.activeTo??''} onChange={e=>patch(p.id,{activeTo:e.target.value||null})}/></label></div></details>)}<div className="staff-footer"><p className="quiet-count">Náhled: {activePeople(draft,state.date,shift).filter(p=>p.role==='operator').length} OP · {activePeople(draft,state.date,shift).filter(p=>p.role==='lead').length} vedoucí</p><button className="primary" disabled={busy} onClick={()=>run(async()=>{await mutate('roster',draft);setSaved(true);})}><Save size={16}/>{busy?'Ukládání…':'Uložit seznam'}</button>{saved&&<span role="status" className="staff-saved">Změny předány k uložení</span>}</div></>}
 </DialogContent></Dialog></>;
}
