import {useState} from 'react';
import {Users,ShieldCheck,ChevronDown} from 'lucide-react';
import {useBoard} from '../services/sitesStore';
import {audit,activePeople,matchPerson,type Shift,type Person} from '../../domain';
import {getDepartmentById} from '../data/departments';
export function TeamRosterSummary({shift,onOpen}:{shift:Shift;onOpen:(tab:'check'|'people',team:'transport'|'vna',name?:string)=>void}){
 const state=useBoard(),check=audit(state.board,state.date,shift),people=activePeople(state.board.roster,state.date,shift);
 const [mobile,setMobile]=useState<'transport'|'vna'>(()=>{try{return localStorage.getItem('zf-kmen-team')==='vna'?'vna':'transport';}catch{return 'transport';}});
 const choose=(team:'transport'|'vna')=>{setMobile(team);try{localStorage.setItem('zf-kmen-team',team);}catch{}};
 const daily=(id:string)=>{const r=check.rows.find(r=>r.person.id===id);if(!r)return 'Vedoucí';if(r.operator?.status==='absence')return r.operator.absenceReason;if(r.operator)return getDepartmentById(r.operator.departmentId)?.name??r.operator.departmentId;return r.note??(r.status==='waiting'?'Čeká na rozpis':'Bez zařazení');};
 const extras=state.board.operators.filter(o=>o.shift===shift&&!people.some(p=>p.id===o.personId)&&matchPerson(o.name,people).length!==1);
 const personRow=(p:Person)=><button className="team-person" key={p.id} onClick={()=>onOpen('check',p.team,p.name)}><span>{p.name}{p.distinction&&<small> · {p.distinction}</small>}</span><small>{daily(p.id)}</small></button>;
 return <section className="kmen-section" aria-label={'Kmen směny '+shift}><div className="kmen-title"><Users size={17}/><b>Kmen směny {shift}</b><span>{state.date}</span></div><div className="team-mobile-tabs">{(['transport','vna'] as const).map(team=><button key={team} aria-pressed={mobile===team} onClick={()=>choose(team)}>{team==='transport'?'Transport':'VNA'} · {check.teams[team].total}</button>)}</div><div className={'team-grid mobile-'+mobile}>{(['transport','vna'] as const).map(team=>{
 const summary=check.teams[team],members=people.filter(p=>p.team===team),lead=members.find(p=>p.role==='lead'),pending=check.rows.filter(r=>r.person.team===team&&['missing','conflict'].includes(r.status));
 return <article className={'team-panel '+team} key={team}><header><h2>{team==='transport'?'Transport':'VNA'}</h2><button onClick={()=>onOpen('people',team)}>Spravovat tým</button></header><div className="team-lead"><ShieldCheck size={15}/>{lead?.name??'Vedoucí není nastaven'}</div><div className="team-counts"><strong>Kmen {summary.total}</strong><span>OP {summary.op}</span><span>PS {summary.ps}</span></div><button className={'team-audit '+(pending.length?'attention':'')} onClick={()=>onOpen('check',team)}>{check.hasImport?`Evidováno ${summary.resolved} · ověřit ${summary.pending}`:'Čeká na dnešní rozpis'}</button>{pending.map(r=><button key={r.person.id} className="team-issue" onClick={()=>onOpen('check',team,r.person.name)}><span>{r.person.name}</span><small>{r.status==='conflict'?'Více záznamů':'Chybí zařazení nebo důvod'}</small></button>)}<details className="team-list"><summary>Seznam týmu <ChevronDown size={15}/></summary>{(['operator','problem_solver'] as const).map(role=><div key={role}><h3>{role==='operator'?'Operátoři':'Problem solveři'} · {members.filter(p=>p.role===role).length}</h3>{members.filter(p=>p.role===role).sort((a,b)=>a.name.localeCompare(b.name,'cs')).map(personRow)}</div>)}{!members.length&&<p>Seznam je zatím prázdný.</p>}</details></article>;
 })}</div>{extras.length>0&&<details className="team-extras"><summary>Výpomoc mimo kmen · {extras.length}</summary>{extras.map(o=><p key={o.id}>{o.name} <span>· {getDepartmentById(o.departmentId)?.name??o.departmentId}</span></p>)}</details>}</section>;
}
